# Logistic Regression (LogReg) Example

This is a SIMPLE sample implementation of Logistic Regression using the `turtles` `LogReg` class and various supporting functions. It skips many of the typical modeling steps: EDA, feature engineering, train/test splits, etc.

The `LogReg` class implements Logistic Regression using Maximum Likelihood Estimation (MLE) for parameter estimation.

In [1]:
import time

from ucimlrepo import fetch_ucirepo

from turtles.stats.glms import LogReg
from turtles.preprocess import one_hot_encode

In [ ]:
full_data = fetch_ucirepo(id=891)

X = full_data.data.features
y = full_data.data.targets

print(type(X))
print(type(y))
print(X.shape)

X.head()

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(253680, 21)

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1,1,1,40,1,0,0,0,0,1,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,25,1,0,0,1,0,0,...,0,1,3,0,0,0,0,7,6,1
2,1,1,1,28,0,0,0,0,1,0,...,1,1,5,30,30,1,0,9,4,8
3,1,0,1,27,0,0,0,1,1,1,...,1,0,2,0,0,0,0,11,3,6
4,1,1,1,24,0,0,0,1,1,1,...,1,0,2,3,0,0,0,11,5,4

In [3]:
y.head()

   Diabetes_binary
0                0
1                0
2                0
3                0
4                0

In [4]:
X.describe()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,0.811420,...,0.951053,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875
std,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,0.391175,...,0.215759,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148
min,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [5]:
cat_cols = []
for col in X.columns:
    if X[col].max() == 1:
        cat_cols.append(col)

In [6]:
X = one_hot_encode(X, columns=cat_cols)
print(X.shape)

(253680, 21)

In [7]:
X = X.to_numpy()
y = y.to_numpy()

print("X:", X.shape)
print("y:", y.shape)

X: (253680, 21)
y: (253680, 1)

In [ ]:
n_model = LogReg(
    method="newton",
    learning_rate=1.0,
    tolerance=0.00001
)

In [9]:
start = time.time()

n_model.fit(X, y)

print("Newtons time to fit:", time.time() - start)
print("Newtons Iterations:", n_model.iterations)
print()

print("Newtons Method Model Summary:\n")
display(n_model.summary())

Newtons time to fit: 0.5630135536193848
Newtons Iterations: 6

Newtons Method Model Summary:

     Variable  Coefficient  Std Error  z-statistic  p-value  [0.025  0.975]
0   Intercept      -7.8362     0.0936     -83.7600   0.0000 -8.0196 -7.6529
1          x0       0.0609     0.0009      67.5988   0.0000  0.0591  0.0626
2          x1       0.5359     0.0081      65.8624   0.0000  0.5200  0.5519
3          x2      -0.0036     0.0009      -4.2531   0.0000 -0.0053 -0.0020
4          x3      -0.0074     0.0008      -9.4540   0.0000 -0.0089 -0.0059
5          x4       0.1236     0.0028      44.1998   0.0000  0.1182  0.1291
6          x5      -0.0308     0.0070      -4.4221   0.0000 -0.0445 -0.0172
7          x6      -0.0515     0.0036     -14.4225   0.0000 -0.0585 -0.0445
8          x7       0.7576     0.0148      51.3323   0.0000  0.7286  0.7865
9          x8       0.5785     0.0136      42.5569   0.0000  0.5519  0.6052
10         x9       1.2440     0.0686      18.1387   0.0000  1.1096  1.3784
11        x10      -0.0104     0.0132      -0.7870   0.4313 -0.0363  0.0155
12        x11       0.1342     0.0251       5.3456   0.0000  0.0850  0.1834
13        x12       0.2204     0.0178      12.3825   0.0000  0.1855  0.2553
14        x13      -0.0518     0.0144      -3.5863   0.0003 -0.0801 -0.0235
15        x14      -0.0499     0.0137      -3.6470   0.0003 -0.0768 -0.0231
16        x15      -0.0332     0.0159      -2.0831   0.0372 -0.0643 -0.0020
17        x16      -0.7692     0.0385     -19.9628   0.0000 -0.8447 -0.6937
18        x17       0.0827     0.0335       2.4700   0.0135  0.0171  0.1483
19        x18       0.0180     0.0230       0.7798   0.4355 -0.0272  0.0631
20        x19       0.1232     0.0170       7.2554   0.0000  0.0899  0.1565
21        x20       0.2581     0.0135      19.1816   0.0000  0.2318  0.2845

## Compare to Statsmodels

Let's compare the `turtles` implementation to `statsmodels`.

In [10]:
import statsmodels.api as sm

In [11]:
Xtrain = sm.add_constant(X)

log_reg = sm.Logit(y, Xtrain)
start = time.time()
sum = log_reg.fit()
print()
print("Statsmodels time to converage: ", time.time() - start)
print()
print(sum.summary())

Optimization terminated successfully.
         Current function value: 0.319662
         Iterations 8

Statsmodels time to converage:  0.8688437938690186

                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:               253680
Model:                          Logit   Df Residuals:                   253658
Method:                           MLE   Df Model:                           21
Date:                Sat, 20 Jun 2026   Pseudo R-squ.:                  0.2083
Time:                        08:00:45   Log-Likelihood:                -81092.
converged:                       True   LL-Null:                   -1.0242e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -7.8362      0.094    -83.760      0.000      -8.020      -7.653
x1             0.0609      0.001     67.599      0.000       0.059       0.063
x2             0.5359      0.008     65.862      0.000       0.520       0.552
x3            -0.0036      0.001     -4.253      0.000      -0.005      -0.002
x4            -0.0074      0.001     -9.454      0.000      -0.009      -0.006
x5             0.1236      0.003     44.200      0.000       0.118       0.129
x6            -0.0308      0.007     -4.422      0.000      -0.044      -0.017
x7            -0.0515      0.004    -14.423      0.000      -0.058      -0.044
x8             0.7576      0.015     51.332      0.000       0.729       0.786
x9             0.5785      0.014     42.557      0.000       0.552       0.605
x10            1.2440      0.069     18.139      0.000       1.110       1.378
x11           -0.0104      0.013     -0.787      0.431      -0.036       0.015
x12            0.1342      0.025      5.346      0.000       0.085       0.183
x13            0.2204      0.018     12.383      0.000       0.186       0.255
x14           -0.0518      0.014     -3.586      0.000      -0.080      -0.023
x15           -0.0499      0.014     -3.647      0.000      -0.077      -0.023
x16           -0.0332      0.016     -2.083      0.037      -0.064      -0.002
x17           -0.7692      0.039    -19.963      0.000      -0.845      -0.694
x18            0.0827      0.033      2.470      0.014       0.017       0.148
x19            0.0180      0.023      0.780      0.436      -0.027       0.063
x20            0.1232      0.017      7.255      0.000       0.090       0.156
x21            0.2581      0.013     19.182      0.000       0.232       0.285
==============================================================================